language: generic
sudo: required # need su permission
services:
  - docker # install copy of docker

before_install:
  - docker build -t nospam1961/docker-react -f Dockerfile.dev .

script: # commands to run test scripts
  # run test and exit by passing CI env var set to true
  - docker run -e CI=true nospam1961/docker-react npm run test