version: "3"
services: # containers
  web: # name
    build: # . indicates that Dockerfile exists. In our case Dockerfile.dev
      context: . # react project folder
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    stdin_open: true # to fix bug associated with Create React App
  tests: # name of image
    build: # . indicates that Dockerfile exists. In our case Dockerfile.dev
      context: . # react project folder
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
    stdin_open: true # to fix bug associated with Create React App
